### PR TITLE
Laravel 5.4 compatibility

### PR DESCRIPTION
**Pull request by mathieutu**
I let you merge and tag it, and add the tag on the readme to be still compatible with previous version...
Thanks!
https://github.com/Superbalist/laravel-pubsub/issues/6

### CODE REVIEW

**Comment by mathieutu** [comment]
I didn't change the `composer.json`, because the new method is not in the container interface, and `illuminate/container` was not tagged yet with it. So it does work even if I find it not really pretty (but we don't really have the choice, right ?).

**Comment by mathieutu** [comment]
Hey guys!
I'm starting to worry a bit, are you still alive ? ^^"

**Comment by akira28** [comment]
Hi guys, any news on this? Should I use @mathieutu fork for the time being?
Thanks!

**Comment by matthewgoslett** [comment]
Hey

Yes sorry we're still active, just been busy.

I'd like to get this fixed in master.
Is there any way we can do some form of version checking here to call make or makeWith so that we can have this work for previous and future versions of Laravel moving forward?

**Comment by akira28** [comment]
you could use the VERSION constant:
`$laravel = app();
return "Your Laravel version is ".$laravel::VERSION;`

**Comment by matthewgoslett** [comment]
I've pushed this up in https://github.com/Superbalist/laravel-pubsub/releases/tag/2.0.3

Thanks!

**Pull request merged**
